source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FCWebViewProgress_Example', :exclusive => true do
  pod "FCWebViewProgress", :path => "../"
end

target 'FCWebViewProgress_Tests', :exclusive => true do
  pod "FCWebViewProgress", :path => "../"

  
end
